### ISSUE TITLE
Profile screen with user information & settings

### ISSUE THREAD

**Issue by Whilsterr** [MotoConnect/motoconnect-mobile#14]

**Comment by Whilsterr** [comment]
Informations affichés ok pour l'instant, en attente de la maj de l'authentification pour adapter l'affichage

**Comment by augustinde** [comment]
La PR a été mergé : https://github.com/MotoConnect/motoconnect-mobile/pull/11
Si tu as des questions n'hésite pas.
Je rajouterais une bonne dose de Doc quand je ferais le readme et le reste
